### PR TITLE
use lowercase html entities:

### LINKED ISSUE #1: HTML Tidy
Search for ADGenKinetics here:
https://build.openmodelica.org/Documentation/tidy.filtered

### PR DESCRIPTION
**Pull request by thorade**
this is a very easy fix for 80% of the HTML warnings reported by HTML Tidy:
https://build.openmodelica.org/Documentation/tidy.filtered
this closes #1

### CODE REVIEW

**Comment by thorade** [comment]
Could this be merged?

**Comment by thorade** [comment]
ping

**Comment by thorade** [comment]
Could this be merged?

**Comment by thorade** [comment]
Could this be merged?

**Comment by AtiyahElsheikh** [comment]
Done!
Thx

**Pull request merged**
